### PR TITLE
Add missing main Ruby file

### PR DESCRIPTION
**Pull request by RKushnir**
Addresses https://github.com/daxtens/fast_secure_compare/issues/2

### CODE REVIEW

**Comment by antonpaisov** [comment]
:+1:

**Comment by daxtens** [comment]
This is causing the Travis tests to fail --- can you address that please?

**Comment by RKushnir** [comment]
@daxtens I'll have a look

**Comment by RKushnir** [comment]
@daxtens So I made the tests pass, but this is confusing. Now I think the code should have been working even without this pull request, as it just adds some redirection - instead of requiring the `*.so` file directly we now require it through `*.rb` file.

**Pull request closed without merging**
